server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/potato
    username: root
    password: tmddn13240.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL8Dialect 이부분이 mysql db라는걸 알려줌, h2~~ 면 h2 씀
    hibernate:   # jPA의 근간
      ddl-auto: create  # create, create-drop, update, validate, none // 사실상 설정 안하면 됨
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true  # query 보여주는것
        format_sql: true  #
    defer-datasource-initialization: true  # sql문이 hibernate 초기화 이후 동작하도록 만들기 위함
  sql:
    init:
      mode: always  # resources에 있는 sql을 모든 데이터베이스에 적용함(embeded: 내장 데이터베이스만, never: 내장, 외부 db모두 적용안함)

jwt:
  header: Authorization
  secret: 54397225e6e1676523acdaba48df130881ab3474cde82e08ceb401637ca0505ed0cc62477b843723d2439648b117619f7d939954bf317d0474394eb261ba1ba9
  access-token-validity: 60000 # 1 min
  refresh-token-validity: 60000 # 1 min